spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instant_blog
    username: root
    password: "x18087477697"
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 5MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9000
  servlet:
    encoding:
      force-response : true

